export const CHANGE_FAVOURITE_LIST_ITEM = 'CHANGE_FAVOURITE_LIST_ITEM'
export const SORT_LIST                  = 'SORT_LIST'
export const CREATE_INITIAL_STATE       = 'CREATE_INITIAL_STATE'
export const CHANGE_LANGUAGE            = 'CHANGE_LANGUAGE'